/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  UserDecryptMultiple,
  UserDecryptMultipleInterface,
} from "../../contracts/UserDecryptMultiple";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "ZamaProtocolUnsupported",
    type: "error",
  },
  {
    inputs: [],
    name: "confidentialProtocolId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052346101d157610011610208565b50466001036100ed57610022610208565b5061002b6101d5565b5f81525f60208201525f60408201525b80517f9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e464970080546001600160a01b039283166001600160a01b03199182161790915560208301517f9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e464970180549184169183169190911790556040928301517f9e7b61f58c47dc699ac88507c4f5bb9f121c03808c5676a8078fe583e4649702805491909316911617905551607b90816102238239f35b4662aa36a703610158576100ff610208565b506101086101d5565b73f0ffdc93b7e186bc2f8cb3daa75d86d1930a433d81527392c920834ec8941d2c77d188936e1f7a6f49c127602082015273be0e383937d564d7ff0bc3b46c51f0bf8d5c311a604082015261003b565b46617a69036101c257610169610208565b506101726101d5565b7350157cffd6bbfa2dece204a89ec419c23ef5755d815273e3a9105a3a932253a70f126eb1e3b589c643dd24602082015273be0e383937d564d7ff0bc3b46c51f0bf8d5c311a604082015261003b565b6373cac13b60e01b5f5260045ffd5b5f80fd5b60405190606082016001600160401b038111838210176101f457604052565b634e487b7160e01b5f52604160045260245ffd5b6102106101d5565b905f82525f60208301525f604083015256fe60808060405260043610156011575f80fd5b5f3560e01c638927b030146023575f80fd5b34603e575f366003190112603e57602090603a6042565b8152f35b5f80fd5b46600103604e57600190565b4662aa36a703605d5761271190565b617a6946146069575f90565b5f199056fea164736f6c634300081b000a";

type UserDecryptMultipleConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UserDecryptMultipleConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UserDecryptMultiple__factory extends ContractFactory {
  constructor(...args: UserDecryptMultipleConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      UserDecryptMultiple & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): UserDecryptMultiple__factory {
    return super.connect(runner) as UserDecryptMultiple__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UserDecryptMultipleInterface {
    return new Interface(_abi) as UserDecryptMultipleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): UserDecryptMultiple {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as UserDecryptMultiple;
  }
}
