/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_AMOUNT"
      | "chaosEngine"
      | "emergencyWithdraw"
      | "feeRecipient"
      | "getEncryptedEntropy"
      | "getFee"
      | "getRequest"
      | "isRequestFulfilled"
      | "owner"
      | "renounceOwnership"
      | "requestEntropy"
      | "requests"
      | "setChaosEngine"
      | "setFeeRecipient"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChaosEngineUpdated"
      | "EntropyFulfilled"
      | "EntropyRequested"
      | "FeeRecipientUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FEE_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chaosEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedEntropy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getFee", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRequestFulfilled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setChaosEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "FEE_AMOUNT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chaosEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRequestFulfilled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "requests", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setChaosEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ChaosEngineUpdatedEvent {
  export type InputTuple = [oldEngine: AddressLike, newEngine: AddressLike];
  export type OutputTuple = [oldEngine: string, newEngine: string];
  export interface OutputObject {
    oldEngine: string;
    newEngine: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyFulfilledEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    hashedConsumer: BytesLike,
    hashedTag: BytesLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    hashedConsumer: string,
    hashedTag: string
  ];
  export interface OutputObject {
    requestId: bigint;
    hashedConsumer: string;
    hashedTag: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    hashedConsumer: BytesLike,
    hashedTag: BytesLike,
    feePaid: BigNumberish
  ];
  export type OutputTuple = [
    requestId: bigint,
    hashedConsumer: string,
    hashedTag: string,
    feePaid: bigint
  ];
  export interface OutputObject {
    requestId: bigint;
    hashedConsumer: string;
    hashedTag: string;
    feePaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRecipientUpdatedEvent {
  export type InputTuple = [
    oldRecipient: AddressLike,
    newRecipient: AddressLike
  ];
  export type OutputTuple = [oldRecipient: string, newRecipient: string];
  export interface OutputObject {
    oldRecipient: string;
    newRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyOracle extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyOracle;
  waitForDeployment(): Promise<this>;

  interface: EntropyOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  chaosEngine: TypedContractMethod<[], [string], "view">;

  emergencyWithdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getEncryptedEntropy: TypedContractMethod<
    [requestId: BigNumberish],
    [string],
    "view"
  >;

  getFee: TypedContractMethod<[], [bigint], "view">;

  getRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        consumer: string;
        tag: string;
        timestamp: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;

  isRequestFulfilled: TypedContractMethod<
    [requestId: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  requests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        consumer: string;
        tag: string;
        encryptedEntropy: string;
        timestamp: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;

  setChaosEngine: TypedContractMethod<
    [newEngine: AddressLike],
    [void],
    "nonpayable"
  >;

  setFeeRecipient: TypedContractMethod<
    [newRecipient: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "chaosEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEncryptedEntropy"
  ): TypedContractMethod<[requestId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish],
    [
      [string, string, bigint, boolean] & {
        consumer: string;
        tag: string;
        timestamp: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRequestFulfilled"
  ): TypedContractMethod<[requestId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "requests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, boolean] & {
        consumer: string;
        tag: string;
        encryptedEntropy: string;
        timestamp: bigint;
        fulfilled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setChaosEngine"
  ): TypedContractMethod<[newEngine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[newRecipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ChaosEngineUpdated"
  ): TypedContractEvent<
    ChaosEngineUpdatedEvent.InputTuple,
    ChaosEngineUpdatedEvent.OutputTuple,
    ChaosEngineUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyFulfilled"
  ): TypedContractEvent<
    EntropyFulfilledEvent.InputTuple,
    EntropyFulfilledEvent.OutputTuple,
    EntropyFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRecipientUpdated"
  ): TypedContractEvent<
    FeeRecipientUpdatedEvent.InputTuple,
    FeeRecipientUpdatedEvent.OutputTuple,
    FeeRecipientUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ChaosEngineUpdated(address,address)": TypedContractEvent<
      ChaosEngineUpdatedEvent.InputTuple,
      ChaosEngineUpdatedEvent.OutputTuple,
      ChaosEngineUpdatedEvent.OutputObject
    >;
    ChaosEngineUpdated: TypedContractEvent<
      ChaosEngineUpdatedEvent.InputTuple,
      ChaosEngineUpdatedEvent.OutputTuple,
      ChaosEngineUpdatedEvent.OutputObject
    >;

    "EntropyFulfilled(uint256,bytes32,bytes32)": TypedContractEvent<
      EntropyFulfilledEvent.InputTuple,
      EntropyFulfilledEvent.OutputTuple,
      EntropyFulfilledEvent.OutputObject
    >;
    EntropyFulfilled: TypedContractEvent<
      EntropyFulfilledEvent.InputTuple,
      EntropyFulfilledEvent.OutputTuple,
      EntropyFulfilledEvent.OutputObject
    >;

    "EntropyRequested(uint256,bytes32,bytes32,uint256)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "FeeRecipientUpdated(address,address)": TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;
    FeeRecipientUpdated: TypedContractEvent<
      FeeRecipientUpdatedEvent.InputTuple,
      FeeRecipientUpdatedEvent.OutputTuple,
      FeeRecipientUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
